#! /bin/sh

#i3 restart
#/home/loic/.config/polybar/scripts/launch.sh
dunstify -i display "Display profile" "$AUTORANDR_CURRENT_PROFILE"
#sleep 1
nitrogen --restore &
#:wqdunstify -i display "Nitrogen restored"

